version: '3.8'

networks:
  candidate-service-network:
    driver: bridge
services:

  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: Candidate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - candidate-service-network

  pgadmin:
    container_name: pgAdmin-inquiry
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8888:80"
    networks:
      - candidate-service-network
    depends_on:
      - postgres
