server:
  port: 8080
  servlet:
    context-path:

spring:
  application:
    name: candidate-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Candidate
  #    url: jdbc:postgresql://postgres:5432/Candidate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
#  sleuth:
#    sampler:
#      probability: 1.0